# fly.toml app configuration file generated for dark-leaf-2782 on 2023-08-23T13:55:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-leaf-2782"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
